/**
 * REDUX CONSTANTS
 */
export const TASKS_REQUEST = 'TASKS_REQUEST';
export const TASKS_RESPONSE_SUCCESS = 'TASKS_RESPONSE_SUCCESS';
export const TASKS_RESPONSE_FAIL = 'TASKS_RESPONSE_FAIL';

export const TASK_ADD_REQUEST = 'TASK_ADD_REQUEST';
export const TASK_ADD_RESPONSE_SUCCESS = 'TASK_ADD_RESPONSE_SUCCESS';
export const TASK_ADD_RESPONSE_FAIL = 'TASK_ADD_RESPONSE_FAIL';

export const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST';
export const TASK_DELETE_RESPONSE_SUCCESS = 'TASK_DELETE_RESPONSE_SUCCESS';
export const TASK_DELETE_RESPONSE_FAIL = 'TASK_DELETE_RESPONSE_FAIL';

export const TASK_UPDATE_REQUEST = 'TASK_UPDATE_REQUEST';
export const TASK_UPDATE_RESPONSE_SUCCESS = 'TASK_UPDATE_RESPONSE_SUCCESS';
export const TASK_UPDATE_RESPONSE_FAIL = 'TASK_UPDATE_RESPONSE_FAIL';

export const REQUEST = 'REQUEST';
export const RESPONSE = 'RESPONSE';
